# Generated by Django 4.0.4 on 2022-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Повна середня освіта', 'Повна середня освіта'), ('Молодший бакалавр', 'Молодший бакалавр'), ('Бакалавр', 'Бакалавр'), ('Магістр', 'Магістр'), ('Доктор філософії / доктор мистецтва', 'Доктор філософії / доктор мистецтва'), ('Доктор наук', 'Доктор наук')], max_length=100),
        ),
    ]
