# Generated by Django 4.0.4 on 2022-07-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Allergist/Immunologist', 'Allergist/Immunologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Cardiologist', 'Cardiologist'), ('Colon and Rectal Surgeon', 'Colon and Rectal Surgeon'), ('Critical Care Medicine Specialist', 'Critical Care Medicine Specialist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Emergency Medicine Specialist', 'Emergency Medicine Specialist'), ('Family Physician', 'Family Physician'), ('Gastroenterologist', 'Gastroenterologist'), ('Geriatric Medicine Specialist', 'Geriatric Medicine Specialist'), ('Hematologist', 'Hematologist'), ('Hospice and Palliative Medicine Specialist', 'Hospice and Palliative Medicine Specialist'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Internist', 'Internist'), ('Medical Geneticist', 'Medical Geneticist'), ('Nephrologist', 'Nephrologist'), ('Neurologist', 'Neurologist'), ('Obstetrician and Gynecologist', 'Obstetrician and Gynecologist'), ('Oncologist', 'Oncologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Osteopath', 'Osteopath'), ('Otolaryngologist', 'Otolaryngologist'), ('Pathologist', 'Pathologist'), ('Pediatrician', 'Pediatrician'), ('Physiatrist', 'Physiatrist'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Podiatrist', 'Podiatrist'), ('Preventive Medicine Specialist', 'Preventive Medicine Specialist'), ('Psychiatrist', 'Psychiatrist'), ('Pulmonologist', 'Pulmonologist'), ('Radiologist', 'Radiologist'), ('Rheumatologist', 'Rheumatologist'), ('Sports Medicine Specialist', 'Sports Medicine Specialist'), ('General Surgeon', 'General Surgeon'), ('Urologist', 'Urologist')], max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='users.appointment'),
        ),
    ]
