# Generated by Django 4.0.4 on 2022-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctor_specialization_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='users.doctor'),
        ),
    ]
