# Generated by Django 4.0.4 on 2022-07-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_organization_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
