# Generated by Django 4.0.4 on 2022-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_organization_doctors_doctor_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='organization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='organization',
            field=models.ManyToManyField(to='users.organization'),
        ),
    ]
