# Generated by Django 4.0.4 on 2022-07-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_sessionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_of_org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
            preserve_default=False,
        ),
    ]
