# Generated by Django 4.0.4 on 2022-07-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_client_phone_remove_doctor_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
