# Generated by Django 4.0.6 on 2022-07-29 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_sessionresult_complaints_sessionresult_examination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionresult',
            name='complaints',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionresult',
            name='diagnosis',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='sessionresult',
            name='examination',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionresult',
            name='payer',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionresult',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionresult',
            name='treatment',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrganizationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CallCenter', 'Call Center'), ('Administrator', 'Administrator')], max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
