# Generated by Django 4.0.6 on 2022-07-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_sessionresult_complaints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstaff',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
            preserve_default=False,
        ),
    ]
